name: base
anchor:
  x: 0
  y: 0
  z: 0
blocks:
  - x: 0
    y: 0
    z: 0
    blockData: minecraft:chest[facing=north,type=single,waterlogged=false]
  - x: 2
    y: 0
    z: 0
    blockData: minecraft:spawner
  - x: 0
    y: 1
    z: 1
    blockData: minecraft:ender_chest[facing=north,waterlogged=false]
  - x: 2
    y: 1
    z: 1
    blockData: minecraft:shulker_box[facing=up]
