debug: false

storage:
  type: sqlite
  sqlite:
    file: violations.db
  mysql:
    host: 127.0.0.1
    port: 3306
    database: antiesp
    username: root
    password: ''
    properties: useSSL=false&characterEncoding=utf8&serverTimezone=UTC
  pool:
    maximum-pool-size: 4
    minimum-idle: 1
    connection-timeout-ms: 10000
