name: MarisGuard
version: '1.1'
author: maris7
main: com.maris7.guard.MarisGuard
api-version: '1.20'
description: Combined guard plugin containing LoadingScreenRemover, RayTraceAntiXray, MarisEsp, and player visibility protection.
load: STARTUP
folia-supported: true
depend:
  - packetevents
libraries:
  - com.zaxxer:HikariCP:7.0.2
  - org.xerial:sqlite-jdbc:3.53.0.0
  - com.mysql:mysql-connector-j:9.7.0
commands:
  esper:
    description: Open ESPER menu and manage ESPER checks
    usage: /esper
    permission: antiesp.esper
  marisguard:
    description: Reload MarisGuard message and check files.
    usage: /marisguard reload
    aliases: [ms]
    permission: marisguard.admin
permissions:
  antiesp.esper:
    default: op
  esper.alerts:
    default: op
  marisguard.admin:
    default: op
